/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SCAL_H_RPCGEN
#define _SCAL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct defvar {
	char x;
	float a;
	float b;
};
typedef struct defvar defvar;

#define MY_PROG 0x23451111
#define MY_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define S_CAL 1
extern  float * s_cal_1(defvar *, CLIENT *);
extern  float * s_cal_1_svc(defvar *, struct svc_req *);
extern int my_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define S_CAL 1
extern  float * s_cal_1();
extern  float * s_cal_1_svc();
extern int my_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_defvar (XDR *, defvar*);

#else /* K&R C */
extern bool_t xdr_defvar ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SCAL_H_RPCGEN */
