/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sCal.h"

bool_t
xdr_defvar (XDR *xdrs, defvar *objp)
{
	register int32_t *buf;

	 if (!xdr_char (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}
